### ISSUE TITLE
Android Studio 环境配置

### ISSUE THREAD

**Issue by zhuzhujoey** [zgh2022/YOLOPv2-YOLOv8-NCNN-Android#1]
大佬，请问Android Studio的环境配置的版本是哪几个版本，我每次build的时候都报错

**Comment by zgh2022** [comment]
android {
    compileSdkVersion 24
    ndkVersion '21.4.7075529'

    defaultConfig {
        applicationId "com.tencent.yolopv2"
        archivesBaseName = "$applicationId"
        minSdkVersion 24
    }

    externalNativeBuild {
        cmake {
            version "3.10.2.4988404"
            path file('src/main/jni/CMakeLists.txt')
        }
    }
记得改local.properties里的路径
然后build工具选corretto-1.8.0_422
