### ISSUE TITLE
大佬您好，关于使用pnnx模型转换ncnn

### ISSUE THREAD

**Issue by Edge-cat** [zgh2022/YOLOPv2-YOLOv8-NCNN-Android#2]
目前onnx2ncnn工具已经停止维护了，在线转换工具也是一样，我看到您的项目是在2024.8.20之后开源的，能否斗胆向您询问转换的一些细节：
比如您使用的pnnx以及ultralytics的版本，以及是否按照飞哥的教程修改了nn中的配置
感谢！

**Comment by zgh2022** [comment]
是的，如果要转换成ncnn项目中可用的onnx模型，确实得按照教程修改那两处，至于ultralytics的版本，我只是看哪串数字顺眼所以选了个8.0.42，在这个区间内的版本之间不会有太大改动，至于pnnx版本，选最新的就好

**Comment by Edge-cat** [comment]
> 本

感谢回复，您的意思是您也使用了pnnx工具对修改后导出的onnx模型进行转换吗，我看到您的模型param下最后层是puemute，而我自己pnnx导出的Yolov8n为concat，我看到其他参考文章说明使用pnnx会删除最后的purmute层，请问您是否遇到这个问题呢？
再次感谢您的回复！

**Comment by zgh2022** [comment]
pnnx工具是这样，但是我直接用的ncnn最新release的包里编译好的x64下的onnx2ncnn.exe进行转换的，最后一层为puemute

**Comment by Edge-cat** [comment]
> pnnx工具是这样，但是我直接用的ncnn最新release的包里编译好的x64下的onnx2ncnn.exe进行转换的，最后一层为puemute
十分感谢您的分享！
